/**
 * PRODUCTS ACTION TYPE
 */
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const FETCH_PRODUCTS_BY_CATEGORY = "FETCH_PRODUCTS_BY_CATEGORY"
export const FETCH_PRODUCT_BY_ID = "FETCH_PRODUCT_BY_ID"
export const FETCH_PRODUCTS_BY_PAGINATION = "FETCH_PRODUCTS_BY_PAGINATION"
export const GET_PRODUCTS_BY_SEARCHING = "GET_PRODUCTS_BY_SEARCHING"
// =========================

/**
 * CATEGORIES ACTION TYPE
 */
export const FETCH_CATEGORIES = "FETCH_CATEGORIES"
/**
 * BRANDS ACTION TYPE
 */
export const FETCH_BRANDS = "FETCH_BRANDS"
